### ISSUE TITLE
setup.py bdist_wininst  error

### ISSUE THREAD

**Issue by binbibi** [saghul/pyuv#195]
Hello,I install pyuv in my PC Successfully,Then I want build a windows installers(.exe),when I edit "python setup.py  bdist_wininst" and run ;I get the error:
![initpintu_](https://cloud.githubusercontent.com/assets/8468934/5680298/2a6dae68-9846-11e4-8afd-55ef81fff36d.jpg)
UnicodeDecodeError:'ascii' code can't decode byte 0xc3 in position 15:
Then I find in setup.py line 19:
author           = "Saúl Ibarra Corretgé" ;your name is not a pure English name ;
So I modify your code :
author           = ("Saúl Ibarra Corretgé").decode("utf-8")
Then work fine , Anothor little shortage is the line 23;
long_description = codecs.open("README.rst", encoding="utf-8").read(),
if I don't modify the code ,the result  windows installers(.exe) is look like:
![result](https://cloud.githubusercontent.com/assets/8468934/5680413/03c01722-9848-11e4-881c-1899800a385f.jpg)
modify the code:
open("README.rst").read().decode("utf-8");Then the result is:
![result](https://cloud.githubusercontent.com/assets/8468934/5680431/3b7b4786-9848-11e4-9185-679dce45da29.jpg)
And it's my Development environment:
![s](https://cloud.githubusercontent.com/assets/8468934/5680464/99f41ed2-9848-11e4-948c-7e8a75c6aa5b.JPG)

Win7X64 Python 2.7.4/amd64  VS2013 ;

**Comment by saghul** [comment]
What local does your system have?

**Comment by binbibi** [comment]
I don't really know the mean "local";I'm a Chinese;the default code page is 936 (ANSI/OEM GBK)

**Comment by saghul** [comment]
> I don't really know the mean "local";I'm a Chinese;the default code page is 936 (ANSI/OEM GBK)

Ok, I'll take a look.

**Comment by binbibi** [comment]
HI,saghul,I found the same error in  your anthor library "pycares", Have you find the reason already?

**Comment by saghul** [comment]
Not really, sorry.

**Comment by saghul** [comment]
Can you try latest v1.x branch please? I just added the utf-8 BOM to the setup.py file, not sure it that will work though.

**Comment by binbibi** [comment]
YES,I try it already ,but same error ;I think maybe your fault;Because I view the source code C:\Python27\Lib\distutils\command\bdist_wininst.py; when I use the "setup.py bdist_wininst";It call the bdist_wininst.py to get the info 
      name             = "pyuv",
      version          = get_version(),
      author           = ("Saúl Ibarra Corretgé"),
      author_email     = "saghul@gmail.com",
      ......
and you can view the func "get_inidata" in "bdist_wininst.py",the error happen the code:
for name in ["author", "author_email", "description", "maintainer",
                     "maintainer_email", "name", "url", "version"]:
 if data:
                info = info + ("\n    %s: %s" % \
                               (string.capitalize(name), escape(data)))

info =  (metadata.long_description or '') + '\n'

The "info" is a Unicode Object;But the ("\n    %s: %s" % (string.capitalize(name), escape(data))) is a 'Utf-8' (when name == 'author',data =='Saúl Ibarra Corretgé');it cause the error the UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
I can review the error from the sample code:
SIC.py
# -*- coding: utf-8 -*-
import Test
Test.test('Saúl Ibarra Corretgé')

Test.py
import string
import chardet
def test(s):
    for ss in s:
        print hex(ord(ss)),
    print ' '
    s2 = string.replace(s, "\n", "\\n")
    info = u'ke'
    s = ("%s:%s" % (string.capitalize('OK'), s2))
    print type(s)
    print s
    print chardet.detect(s)
    info = info + s      #error
    print info
I am sorry I write the code here;so i think you should patch your name to 'Unicode';

**Comment by saghul** [comment]
Closing, I think https://github.com/saghul/pyuv/commit/0c549f762359f7282184d1a6f6b86bff99ec37c2 fixed it.
