### ISSUE TITLE
pyuv handler object should can change to python socket object

### ISSUE THREAD

**Issue by boytm** [saghul/pyuv#196]
I want use socket.setsockopt() to change socket options, but the pyuv tcp and udp handlers don't have this method.  So I must be change pyuv handler object to python scoket object. But this change need some property , see below.

    socket.fromfd(fd, family, type[, proto]) 

Wish tcp and udp handler have property family, type, proto.

**Comment by saghul** [comment]
It's possible now, here is an example: https://github.com/saghul/pyuv/commit/516e0797a717d77012f9b2ac5e83b6e9d6eafce5
