### ISSUE TITLE
Pip install throws UnicodeDecodeError

### ISSUE THREAD

**Issue by scpio2** [saghul/pyuv#200]
referring to: http://stackoverflow.com/questions/30891721/installing-python-package-throws-unicodedecodeerror

**Comment by saghul** [comment]
What does the following print in your system? (try it in a Python console or IDLE):

~~~~
import locale
print locale.getpreferredencoding()
~~~~

**Comment by scpio2** [comment]
thanks for the quick answer :-)

Python 2.7:
locale.getpreferredencoding() -> cp1252
sys.getdefaultencoding -> 'ascii'

Python 3.4:
locale.getpreferredencoding() -> cp1252
sys.getdefaultencoding -> 'utf-8'

**Comment by saghul** [comment]
Thanks for the feedback! Can you try to apply this patch?

~~~~
diff --git a/setup_libuv.py b/setup_libuv.py
index a7e6b5e..937b9fa 100644
--- a/setup_libuv.py
+++ b/setup_libuv.py
@@ -1,6 +1,7 @@
 
 import ast
 import errno
+import locale
 import os
 import platform
 import shutil
@@ -15,6 +16,7 @@ from distutils.errors import DistutilsError
 
 
 PY3 = sys.version_info[0] == 3
+DEFAULT_LOCALE = locale.getpreferredencoding() or 'utf-8'
 
 
 def makedirs(path):
@@ -46,8 +48,8 @@ def exec_process(cmdline, silent=True, input=None, **kwargs):
         stdout, stderr = sub.communicate(input=input)
         returncode = sub.returncode
         if PY3:
-            stderr = stderr.decode('utf-8')
-            stdout = stdout.decode('utf-8')
+            stderr = stderr.decode(DEFAULT_LOCALE)
+            stdout = stdout.decode(DEFAULT_LOCALE)
         if not silent:
             sys.stdout.write(stdout)
             sys.stderr.write(stderr)
@@ -88,7 +90,7 @@ def prepare_windows_env(env):
     try:
         sub = subprocess.Popen(cmd, stdout=subprocess.PIPE)
         stdout, _ = sub.communicate()
-        version = ast.literal_eval(stdout.decode('utf-8').strip())
+        version = ast.literal_eval(stdout.decode(DEFAULT_LOCALE).strip())
         if version == (2, 7):
             return  # Python on PATH is fine
     except OSError:
~~~~

**Comment by scpio2** [comment]
The error message has changed to the following:

    C:\Users\Niko\Downloads\pyuv-1.x\pyuv>python setup.py build_ext --inplace
    running build_ext
    Downloading libuv...
    Building libuv...
    Using "C:\Python27\python.exe" to build libuv...
    Traceback (most recent call last):
      File "setup.py", line 42, in <module>
        sources = ['src/pyuv.c'],
      File "C:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Niko\Downloads\pyuv-1.x\pyuv\setup_libuv.py", line 148, in buil
    d_extensions
        self.get_libuv()
      File "C:\Users\Niko\Downloads\pyuv-1.x\pyuv\setup_libuv.py", line 199, in get_
    libuv
        build_libuv()
      File "C:\Users\Niko\Downloads\pyuv-1.x\pyuv\setup_libuv.py", line 185, in buil
    d_libuv
        exec_process(['cmd.exe', '/C', 'vcbuild.bat', libuv_arch, 'release'], cwd=se
    lf.libuv_dir, env=env, shell=True, silent=not self.libuv_verbose_build)
      File "C:\Users\Niko\Downloads\pyuv-1.x\pyuv\setup_libuv.py", line 52, in exec_
    process
        stdout = stdout.decode(DEFAULT_LOCALE)
      File "C:\Python34\lib\encodings\cp1252.py", line 15, in decode
        return codecs.charmap_decode(input,errors,decoding_table)
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4038: cha
    racter maps to <undefined>

**Comment by saghul** [comment]
Sigh... I'll try to reproduce it locally and come back to you.

**Comment by scpio2** [comment]
Thanks, I appreciate it. Eager to use pyuv ;-)

**Comment by saghul** [comment]
Can you open cmd.exe and run the following commend?

~~~~
chcp
~~~~

**Comment by scpio2** [comment]
Yep.

chcp >> Active code page: 850

**Comment by saghul** [comment]
@scpio2 I cannot reproduce it, sigh. Can you try this patch? (undo anything you did before)

~~~~
diff --git a/setup_libuv.py b/setup_libuv.py
index a7e6b5e..43c455b 100644
--- a/setup_libuv.py
+++ b/setup_libuv.py
@@ -46,8 +46,8 @@ def exec_process(cmdline, silent=True, input=None, **kwargs):
         stdout, stderr = sub.communicate(input=input)
         returncode = sub.returncode
         if PY3:
-            stderr = stderr.decode('utf-8')
-            stdout = stdout.decode('utf-8')
+            stderr = stderr.decode(sys.stderr.encoding)
+            stdout = stdout.decode(sys.stdout.encoding)
         if not silent:
             sys.stdout.write(stdout)
             sys.stderr.write(stderr)
@@ -88,7 +88,7 @@ def prepare_windows_env(env):
     try:
         sub = subprocess.Popen(cmd, stdout=subprocess.PIPE)
         stdout, _ = sub.communicate()
-        version = ast.literal_eval(stdout.decode('utf-8').strip())
+        version = ast.literal_eval(stdout.decode(sys.stdout.encoding).strip())
         if version == (2, 7):
             return  # Python on PATH is fine
     except OSError:
~~~~

**Comment by scpio2** [comment]
Hey, looking great. libuv is successfully being built. I'm left with some linker errors (error 1120) from Visual Studio, which most likely aren't related to this. I'm reinstalling all necessary building components and will let you know if it's working.

**Comment by saghul** [comment]
Thanks!

**Comment by scpio2** [comment]
hmmm, still not working after the reinstall. Here is my sdk shell output:

![error1120](https://cloud.githubusercontent.com/assets/12936596/8237132/6cba9950-15ed-11e5-82b9-2c09495657dd.png)

However I tried my setup by building pycrypto and didn't encounter any errors.

**Comment by saghul** [comment]
@scpio2 ah, I forgot to link with the new libraries, can you apply this patch and try again? (leave the encoding patch applied)

~~~~
diff --git a/setup_libuv.py b/setup_libuv.py
index 43c455b..8b95168 100644
--- a/setup_libuv.py
+++ b/setup_libuv.py
@@ -155,6 +155,8 @@ class libuv_build_ext(build_ext):
             self.compiler.add_library('advapi32')
             self.compiler.add_library('iphlpapi')
             self.compiler.add_library('psapi')
+            self.compiler.add_library('shell32')
+            self.compiler.add_library('userenv')
             self.compiler.add_library('ws2_32')
         elif sys.platform.startswith('freebsd'):
             self.compiler.add_library('kvm')
~~~~

**Comment by scpio2** [comment]
Type conversion warnings remain, but everything is working now! Thanks ;-)

**Comment by saghul** [comment]
Fantastic! Let me commit that then! Thanks for your help debugging this.
