### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by zii** [saghul/pyuv#201]
I run python setup.py install on windows, there was a link error:
libuv.lib(util.obj) : error LNK2001: unresolved external symbol __imp__GetUserProfileDirectoryW@12

Then I add this line into src/pyuv.h, it works!
#pragma comment(lib, "Userenv.lib")

**Comment by saghul** [comment]
Hum, we do link with userenv: https://github.com/saghul/pyuv/blob/v1.x/setup_libuv.py#L159 can you paste the entire build output? Thanks!

**Comment by zii** [comment]
Oh! My setup_libuv.py doesn't have this:
<b>self.compiler.add_library('userenv')</b>

Download from here:
https://github.com/saghul/pyuv/archive/pyuv-1.1.0.zip

**Comment by zii** [comment]
![pyuv-error](https://cloud.githubusercontent.com/assets/81924/9101549/f11d3768-3c1a-11e5-8147-99f77f097f42.png)

**Comment by zii** [comment]
running install
running bdist_egg
running egg_info
writing pyuv.egg-info\PKG-INFO
writing top-level names to pyuv.egg-info\top_level.txt
writing dependency_links to pyuv.egg-info\dependency_links.txt
reading manifest file 'pyuv.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyuv.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
No need to build libuv.
building 'pyuv._cpyuv' extension
C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DWIN32=1 -ID:\Python27\include -ID:\Python27\PC -Ideps\libuv\include /Tcsrc/pyuv.c /Fobuild\temp.win32-2.7\Release\src/pyuv.obj
pyuv.c
d:\d\pyuv-pyuv-1.1.0\src\process.c(187) : warning C4244: 'function' : conversion from 'int64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(220) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(221) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(222) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(223) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(224) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(225) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(226) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(227) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(228) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(229) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(230) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(231) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(232) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
d:\d\pyuv-pyuv-1.1.0\src\util.c(233) : warning C4244: 'function' : conversion from 'uint64_t' to 'long', possible loss of data
C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:D:\Python27\libs /LIBPATH:D:\Python27\PCbuild advapi32.lib iphlpapi.lib psapi.lib ws2_32.lib /EXPORT:init_cpyuv build\temp.win32-2.7\Release\src/pyuv.obj deps\libuv\Release\lib\libuv.lib /OUT:build\lib.win32-2.7\pyuv\_cpyuv.pyd /IMPLIB:build\temp.win32-2.7\Release\src\_cpyuv.lib /MANIFESTFILE:build\temp.win32-2.7\Release\src\_cpyuv.pyd.manifest /NODEFAULTLIB:libcmt /LTCG
   Creating library build\temp.win32-2.7\Release\src\_cpyuv.lib and object build\temp.win32-2.7\Release\src\_cpyuv.exp
libuv.lib(util.obj) : error LNK2001: unresolved external symbol __imp__GetUserProfileDirectoryW@12
build\lib.win32-2.7\pyuv\_cpyuv.pyd : fatal error LNK1120: 1 unresolved externals
error: command '"C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\link.exe"'
failed with exit status 1120

**Comment by saghul** [comment]
Please install pyuv from git, using the v1.x branch. The patch fixing this will be part of the next relase.

**Comment by zii** [comment]
Thank you, saghul!
