### ISSUE TITLE
SSL example?

### ISSUE THREAD

**Issue by schlamar** [saghul/pyuv#207]
In your blog post (http://code.saghul.net/index.php/2013/01/23/tls-connections-with-pyuv-and-pyopenssl/) you talk about SSL support is pretty easy by connecting `pyuv.Poll` with `ssl` from the standard library. Do you have an example somewhere? :)

**Comment by saghul** [comment]
It should be part of the post, as a few Gists. Have they become unavailable?

**Comment by schlamar** [comment]
There is only an example with OpenSSL but not with ssl + pyuv.Poll...

**Comment by saghul** [comment]
Ah, that. At the time of that writing there was no BIO API in the ssl module. That made it to Python 3.5.0, if I'm not mistaken, and I never got the time to give it a go; a TCP handle + PyOpenSSL is all I tried.

Feel free to send a PR with an example (can be Python 3.5 only) if you get around making one ;-)
