### ISSUE TITLE
windows xp 32 bit system crash

### ISSUE THREAD

**Issue by xzzh999** [saghul/pyuv#209]
when make python project to package use bbfreeze and esky, it works well on win7/win8 system,but when put the package to windows XP 32 bit system, it show as follow:

         Traceback (most recent call last):
         File "import_depends.py", line 163, in init import_depends (import_depends.c:2975)
         File ".\depends.zip\pyuv\__init__.py", line 9, in <module>
         ImportError: DLL load failed: 找不到指定的程序(can not find match program)。

import_depends.py just look likes this:
        
         import PIL
         import pyuv
         import sqlalchemy
         ...
         
I convert it to c code by cython and called it by a C++ application,and pyuv is just in depends.zip,and the C extension _cpyuv.pyd just renamed to pyuv._cpyuv.pyd by esky in the app's folder.

I also tried direct call LoadLibrary to load pyuv._cpyuv.pyd or _cpyuv.pyd,  the error changed to:

          无法定位输入点_ftol2于动态链接库msvcrt.dll
          (can not locate  _ftol2 from dynamic dll msvcrt.dll)

but when i copied the full pyuv folder to app's folder(not import from zip),it works well again. I already installed vc90/vc100 runtime on the xp system.

**Comment by saghul** [comment]
To be honest, I have no idea... what you can try is to use Dependency Walker to see if there is a DLL missing.

**Comment by xzzh999** [comment]
Thank you for your reply, I already looked dependency but because the app is a c++ python vm,this didn't help much. the xp system is new installed on vmware,so it has no enviroment problem,now i just copy pyuv folder to app's folder(not in a zip file) as a temporary worked solution.I think i can compile pyuv on xp system but not on win7 to solve this.

**Comment by saghul** [comment]
No follow-up and nothing actionable on my side (that I know of). Closing.
