### ISSUE TITLE
A "TypeError: an integer is required" on python examples/echo-server-poll.py

### ISSUE THREAD

**Issue by alex8224** [saghul/pyuv#212]
The traceback as below:
ERROR:root:<__main__.Server object at 0x7fe54966da50>: error accepting a connection --> stopping
Traceback (most recent call last):
  File "echo-server-poll.py", line 113, in io_cb
    self.conns[address] = Connection(sock, address, self.loop)
  File "echo-server-poll.py", line 26, in __init__
   ** self.watcher = pyuv.Poll(loop, self.sock._sock) ** 
TypeError: an integer is required
DEBUG:root:<__main__.Server object at 0x7fe54966da50>: stopping

**Comment by saghul** [comment]
Thanks! I pushed a fix, can you try again now?

**Comment by alex8224** [comment]
@saghul Yes, it worked. :+1:

**Comment by saghul** [comment]
Great! Thanks for the report and confirmation!
