### ISSUE TITLE
Aborted message issue in pyuv

### ISSUE THREAD

**Issue by countofkrakow** [saghul/pyuv#213]
Hi, 

I've been having the same issue as the user on this thread: https://github.com/saghul/pyuv/issues/197
I'm not quite sure what you mean by your solution of using pyuv.util.guess_handle_type and pyuv.fs.* to deal with a redirected stdin.

Here's a simple repro. 
```
import sys
import pyuv
def on_pipe_read(handle, data, error):
    print data

loop = pyuv.Loop.default_loop()
std_in = pyuv.Pipe(loop)
std_in.open(sys.stdin.fileno())
std_in.start_read(on_pipe_read)
loop.run()
```
Would it be possible to get an example of how to do this workaround in my case?
Thanks!

**Comment by saghul** [comment]
Sorry for the delay, I must have missed this notification :-S Basically, Pipe objects cannot work with regular files. So you can use pyuv.util.guess_handle_type and it it returns UV_FILE then use pyuv.fs.open instead of a Pipe object.
