### ISSUE TITLE
Mutex is not reentrant in Linux  but it is in Windows 64.

### ISSUE THREAD

**Issue by rafaelolg** [saghul/pyuv#216]
The given code freezes in Linux but it doesn't in Windows.
 It is probably related to libuv `uv_mutex_init`

```
import pyuv
m = pyuv.thread.Mutex()
m.lock()
m.lock()
print "if it reached here the lock is reentrant"
```

**Comment by saghul** [comment]
Sorry for the delay, I'll look into this as soon as I can.

**Comment by saghul** [comment]
Closing since it's a libuv issue: https://github.com/libuv/libuv/issues/1022
