### ISSUE TITLE
pyuv._cpyuv.error.FSEventError: (-28, 'no space left on device') on filesystem watch

### ISSUE THREAD

**Issue by crdoconnor** [saghul/pyuv#218]
This is occurring when trying to call 'start' and attach a handle to a pyuv.fs.FSEvent on Ubuntu. It's weird because:

* It's watching a file for filesystem events, not writing.
* There's plenty of space left on all filesystems.

The code runs fine on plenty of other machines (both Linux and Mac).

Python version: 3.4.3

Output of uname -a::

    4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bnoordhuis** [comment]
Bump the `fs.inotify.max_user_instances` and/or `fs.inotify.max_user_watches` sysctls on your machine.  That ENOSPC eror means you're hitting the system limits.

**Comment by crdoconnor** [comment]
Solved, thanks!
