### ISSUE TITLE
OpenWRT build

### ISSUE THREAD

**Issue by joustava** [saghul/pyuv#220]
I would like to cross compile this library to OpenWRT
I have setup a VM with the OpenWRT toolkit for cross compiling installed according to this [tutorial](https://wiki.onion.io/Tutorials/Cross-Compile). At this point I have no idea how I would go about doing this. I am new to OpenWRT and cross compiling and also have only basic Python knowledge.

Any help appreciated.

**Comment by saghul** [comment]
I have no experience with this, sorry. I hope someone can chime in and help
you out!
