### ISSUE TITLE
Building pyuv with MinGW-w64

### ISSUE THREAD

**Issue by equalsraf** [saghul/pyuv#224]
I've been trying to build pyuv on MSYS2 i.e. MinGW-w64. The usual `python setup.py build_ext`fails with the following errors

```
x86_64-w64-mingw32-gcc: error: deps\libuv\Release\lib\libuv.lib: No such file or directory
x86_64-w64-mingw32-gcc: error: /NODEFAULTLIB:libcmt: No such file or directory
x86_64-w64-mingw32-gcc: error: /LTCG: No such file or directory
```

the first error is looking for libuv, I expected to work around it with --use-system-libuv, but got this instead

```
$ python setup.py build_ext --use-system-libuv
running build_ext
error: using a system provided libuv is unsupported on Windows
```

The other two errors are just MSVC compiler options being passed to MinGW. The following patch works around all of them

``` diff
diff --git a/setup_libuv.py b/setup_libuv.py
index 39d6b6c..ae97171 100644
--- a/setup_libuv.py
+++ b/setup_libuv.py
@@ -147,8 +147,6 @@ class libuv_build_ext(build_ext):
     def build_extensions(self):
         self.force = self.force or self.libuv_force_fetch or self.libuv_clean_compile
         if self.use_system_libuv:
-            if sys.platform == 'win32':
-                raise DistutilsError('using a system provided libuv is unsupported on Windows')
             self.compiler.add_library('uv')
         else:
             if sys.platform == 'win32':
@@ -163,7 +161,8 @@ class libuv_build_ext(build_ext):
             self.compiler.add_library('rt')
         elif sys.platform == 'win32':
             self.extensions[0].define_macros.append(('WIN32', 1))
-            self.extensions[0].extra_link_args.extend(['/NODEFAULTLIB:libcmt', '/LTCG'])
+            if self.compiler.compiler_type != 'mingw32':
+                self.extensions[0].extra_link_args.extend(['/NODEFAULTLIB:libcmt', '/LTCG'])
             self.compiler.add_library('advapi32')
             self.compiler.add_library('iphlpapi')
             self.compiler.add_library('psapi')
```

I checked the log, and any mention of MinGW was removed in 2013, but its not clear why. Would it be ok to start a PR for MinGW-w64?
At least in MSYS2, event without the automatic libuv build step, its pretty useful to be able to just pip install pyuv.

**Comment by saghul** [comment]
Back then, then MSYS2 ecosystem wasn't as awesome as it is right now IIRC :-)

I'd be ok bringing MinGW support back, but only for MSYS2 / MinGW-w64, so using the system provided libuv, as you suggested.  If you send a PR I'll be open to merging it.

**Comment by equalsraf** [comment]
Opened a PR

> I'd be ok bringing MinGW support back, but only for MSYS2 / MinGW-w64, so using the system provided libuv, as you suggested. If you send a PR I'll be open to merging it.

I think the regular UNIX recipe for libuv should work in MSYS2 too, but it is failing, but its some sort of issue with my environment.

**Comment by saghul** [comment]
> Opened a PR

Thanks!

> I think the regular UNIX recipe for libuv should work in MSYS2 too, but it is failing, but its some sort of issue with my environment.

What kind of error are you getting?

**Comment by equalsraf** [comment]
Missing aclocal file, its looking for xsize.m4 in the wrong path /msys64/usr/share instead of /usr/share. Just like this one https://github.com/kwhat/jnativehook/issues/89, so maybe its a problem with my instalation.

**Comment by saghul** [comment]
> Opened a PR

Thanks!

> I think the regular UNIX recipe for libuv should work in MSYS2 too, but it is failing, but its some sort of issue with my environment.

What kind of error are you getting?
