### ISSUE TITLE
Skipping loop round or some runtime quantization?

### ISSUE THREAD

**Issue by catroot** [saghul/pyuv#226]
I've didn't got info about skipping a loop round inside loop handlers.
Is there some round bypass logic realized?

It will be nice if event loop supports delivering to handler a configured time quants for execution. 
Achieving some configurable loop slippage for handlers will be awesome feature.

For now, with massive counting/computing inside a handler - a whole loop gets hang. Sadly.

**Comment by catroot** [comment]
it seems, that libuv itself doesn't have such things..

**Comment by saghul** [comment]
I'm afraid that's not something libuv implements.  Moreover, given that libuv is single threaded, I'm not sure how it could be done, if a handler is busy doing some computations then by who and how does it get interrupted?
