### ISSUE TITLE
pyuv.TCP callback for client disconnect event?

### ISSUE THREAD

**Issue by catroot** [saghul/pyuv#228]
How to correctly determine event of TCP server when client has closed connection?
pyuv.TCP.shutdown() din't react on that event.

Where to catch this event?

PS. Even pyuv.TCP.writable returns true on closed connection handler...

**Comment by saghul** [comment]
> How to correctly determine event of TCP client has closed connection?

You'll get the read callback called with an error.

> pyuv.TCP.shutdown() din't react on that event.

Shutdown just closes one direction of the connection, it doesn't completely disconnect from the remote peer.

> Where to catch this event?
> 

The read callback. UV_EOF means the connection is closed cleanly, for example.

> PS. Even pyuv.TCP.writable returns true on closed connection handler...

Yeah, it's an ill-named property indeed, I shouldn't have exposed it :-S

**Comment by catroot** [comment]
> The read callback. UV_EOF means the connection is closed cleanly, for example.

But connection closing doesn't fire UV_EOF message from peer.

I have scheduled once per second try checks for pyuv.TCP.fileno() on connected handlers - it raises exception "Handle is closing/closed", but no other events triggers for client disconnection.

**Comment by bnoordhuis** [comment]
The stress is on the word 'cleanly'.  If the peer disappears or simply stops sending, there is no way to detect that except through the usual TCP timeout mechanism - which can be anywhere from minutes to hours so if you want something deterministic, you need to maintain an inactivity timer.

**Comment by catroot** [comment]
And there is no way to catch the event changing connection state to "Handle is closing/closed" condition?
Because there is no situation with "lost" client, connection was really closed without apropriate events, even if it was made from localhost.

**Comment by catroot** [comment]
If connection is still valid, why calling fileno() on it raises pyuv._cpyuv.error.HandleClosedError?

**Comment by saghul** [comment]
I'm having a hard time following you here.  Can you post some code?

**Comment by catroot** [comment]
I checked out. 

> That only happens if you call handle.close()

Really, if calling explicitly handle.close() start_read callback will not recieve any error or message.
Pls add to examples some checks for errors conditions in start_read callback.
I've got -4095 and -105 errors.

**Comment by saghul** [comment]
Again, please, paste some code here.  I'm still struggling to fifgure out what problem you run into.  If you call handle.close() the connection is torn down on the spot.  If the remote closes the connection you'll get an error in the read callback, but you still need to close the handle.

In case it helps, have a look at the extensive test suite.

**Comment by catroot** [comment]
That was my misunderstood for the connection handling logic.

> If the remote closes the connection you'll get an error in the read callback, but you still need to close the handle.

Yes, for now it`s all right with connection life cycle handling.

**Comment by catroot** [comment]
Here is the  TCP connections test:
```python
class server():
    def __init__(self):
        import pyuv, signal
        loop=pyuv.Loop()
        srv=pyuv.TCP(loop)
        srv.bind(("127.0.0.1", 9000))
        srv.listen(self.cb, 50)
        signal_h = pyuv.Signal(loop)
        signal_h.start(self.signal_cb, signal.SIGINT)
        self.connections = 0
        loop.run()

    def cb(self, handle, error):
        import pyuv
        if error is None:
            client = pyuv.TCP(handle.loop)
            handle.accept(client)
            client.start_read(self.start_read)
            self.connections += 1
        else:
            print("Error on cb:", error)

    def start_read(self, handle, bytes_data, error):
        if error is not None:
            self.connections -=1
            handle.close()
            print("Closed connection. Connections left:", self.connections)
        else:
            print("Data recieved:", bytes_data, "Connections:", self.connections, "Error:", error)

    def signal_cb(self, handle, signum):
        handle.loop.stop()
        print("\nServer conenctions active:", self.connections)
        print("\nSERVER loop stopped.")


class client():
    def __init__(self):
        import pyuv, signal
        self.connections = []
        loop=pyuv.Loop()
        for i in range(100):
            clnt=pyuv.TCP(loop)
            clnt.connect(("127.0.0.1", 9000), self.cb)
            self.connections.append(clnt)
        signal_h = pyuv.Signal(loop)
        signal_h.start(self.signal_cb, signal.SIGINT)
        loop.run()

    def cb(self, handle, error):
            handle.write(b"Hello server!\n")
            self.connections.remove(handle)
            handle.close()
    def signal_cb(self, handle, signum):
        handle.loop.stop()
        print("\nClient connections active:", len(self.connections))
        print("\nCLIENT loop stopped.")



if __name__ == "__main__":
    from  multiprocessing import Process, Queue
    Process(target=server, args=()).start()
    Process(target=client, args=()).start()


```
