### ISSUE TITLE
Pipe writing to spawn process

### ISSUE THREAD

**Issue by LitBull** [saghul/pyuv#229]
I'm trying to write in a process stdin from a pipe. However, every time I make a Pipe.write(data) appear an error: (-4047, 'broken pipe')
I can't find in examples, Tests or ReadTheDocs the solution. 
This is a code snipet:

class myRead():
    def __init__(self, mypipe):
        self.myPipe=pyuv.Pipe(mypipe,True)

    def on_read(self, handle, ip_port, flags, data, error):
        if data is not None:
            #handle.send(ip_port, data)
            #print( ''.join('{:02x}'.format(x) for x in data[14:-2]))
            self.myPipe.write(data[14:-2])

if __name__ == '__main__':
    loop = pyuv.Loop.default_loop()
    myHandle=myRead(loop)    

    server = pyuv.UDP(loop)
    server.bind(("", 21000), pyuv.UV_UDP_REUSEADDR)
    server.set_multicast_interface ("0.0.0.0")
    server.set_membership("236.10.100.30",pyuv.UV_JOIN_GROUP)
    server.start_recv(myHandle.on_read)

    signal_h = pyuv.Signal(loop)
    signal_h.start(signal_cb, signal.SIGINT)
     StdIO=[]
    #StdIO.append(pyuv.StdIO(flags=pyuv.UV_IGNORE))
    StdIO.append(pyuv.StdIO(stream=myHandle.myPipe,  flags=pyuv.UV_READABLE_PIPE))
    #Process setup
    child =pyuv.Process.spawn(loop, args=s,executable='sox',  exit_callback=proc_exit_cb,stdio=StdIO)    
    loop.run()
    print("Stopped!")

What is the right way to connect the output of the pipe to the input (stdin) of the spawned process?

I've done a similar code for C# and works perfectly. I'd like to do it with python for a better portability.

Thank you.

**Comment by schlamar** [comment]
You are probably missing the `pyuv.UV_CREATE_PIPE` flag.

You can find a complete example in test_process.py: https://github.com/saghul/pyuv/blob/v1.x/tests/test_process.py#L187
