### ISSUE TITLE
Ditch the libuv build system and add libuv sources

### ISSUE THREAD

**Issue by schlamar** [saghul/pyuv#240]
I opened this to track your proposal from https://github.com/libuv/libuv/pull/1284#issuecomment-305099237.

I really like your idea of ditching the libuv build system. 

However I would first concentrate on getting a new release with Python 3.6 wheels on PyPI so all these build issues will become a low priority.

**Comment by saghul** [comment]
Sure. We could bump libuv to 1.12.0 which doesn't include the problematic patch and then do the build-system refactor.

**Comment by schlamar** [comment]
Ref https://github.com/saghul/pycares/commit/a3c4e7fe7b3e593bdd461adb8010af70cfaf95b9

**Comment by saghul** [comment]
PR landed!
