### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by schlamar** [saghul/pyuv#242]
I guess it's time to make a new release with Python 3.6 wheels :)

**Comment by saghul** [comment]
I landed all PRs, so we should be in good shape for a release. I'll try to get one done over the weekend. First I need to remember how on earth I made releases :-P

**Comment by saghul** [comment]
Done! 1.4.0 is out and about. Wheels for Linux and Windows are out: https://pypi.python.org/pypi/pyuv/1.4.0
