### ISSUE TITLE
Support abstract socket addresses in Pipe.bind/Pipe.connect

### ISSUE THREAD

**Issue by geertj** [saghul/pyuv#248]
As per:

https://github.com/joyent/libuv/issues/1486#issuecomment-56337265

would you accept a patch to add abstract socket support to Pipe.bind() and Pipe.listen()?

This would be Linux only, and fail on non-Linux (probably with UV_EINVAL?)

On Linux this would create an AF_UNIX socket, call connect() or bind(), then do do a uv_pipe_open() on the FD. I investigated this as some point in the past, and I remember that both operations never block on Linux (these are local sockets), so I'd not do anything complicated for handling EINTR. Instead I would make the FD non-blocking only after it is successfully bound/connected, and I would depend on Linux not to block (or worst-case block for a very small amount of time).

**Comment by geertj** [comment]
PR #250

**Comment by saghul** [comment]
PR landed!
