### ISSUE TITLE
pip installation failure on Windows 10

### ISSUE THREAD

**Issue by mqudsi** [saghul/pyuv#253]
Similar to previous issues #221 and #219 from May 2016 that predated the latest release, I'm unable to install pyuv via pip3 under Windows 10 x64.

I have python27 and python36 installed and accessible to pip without issue.

I've attached the pip install log.

[pyuv install log.txt](https://github.com/saghul/pyuv/files/1107171/pyuv.install.log.txt)

**Comment by saghul** [comment]
Can you try the latest code in the v1.x branch? We overhauled the build system and it should work now.
