### ISSUE TITLE
Tasks scheduled via loop.queue_work()

### ISSUE THREAD

**Issue by yoonghm** [saghul/pyuv#260]
We would queue callable functions into default loop's thread pool. There are some works to be done:

1.  Is it possible to pass argument to the thread? I use global variable for each thread which is cumbersome.
2.  The list object loop.handles is not updated. I believe this is correct but it is not documented.
3.  The callable callback functions in `loop.queue_work()` is not called.

```
import time
import pyuv

sleep_sec = 1
task1_done= False

def task1():
  global sleep_sec
  global task1_done
  print(f'task1() entered')
  time.sleep(sleep_sec)
  task1_done = True
  print(f'task1() exited')

def task1_cb(errorno):
  print(f'task1 started')
  print(f'error = {errorno}')
  
loop = pyuv.Loop.default_loop()
wr = loop.queue_work(task1, task1_cb)

time.sleep(sleep_sec + 1)
loop.stop()
```

**Comment by saghul** [comment]
1. Look into functools.partial
2. There is no handle. What you get back is a request. This is documented.
3. You haven't called loop.run()

**Comment by yoonghm** [comment]
Thanks. It is working now. Below is the working example.

```
import time
from functools import partial
import pyuv

def task1(sec):
  global task1_done
  print(f'task1() entered')
  time.sleep(sec)
  print(f'task1() exited')

def task1_cb(errorno):
  print(f'task1 started')
  print(f'error = {errorno}')
  
loop = pyuv.Loop.default_loop()
wr = loop.queue_work(partial(task1, 1), task1_cb)
loop.run()

time.sleep(2)
loop.stop()
```
