### ISSUE TITLE
An error in Poll handles example

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [saghul/pyuv#274]
In https://github.com/saghul/pyuv/blob/v1.x/examples/echo-server-poll.py#L40
If a EAGAIN/EWOULDBLOCK exception is raised from `socket.recv`, it is caught and execution continues, local variable `data` is left unassigned, then a `UnboundLocalError` occured on the `if` test follows.

How should it be fixed, by calling `watcher.start(UV_READABLE, io_cb)` again to retry?

**Comment by MichaelSuen-thePointer** [comment]
Same issue in function `handle_write`

**Comment by saghul** [comment]
It should just return, since it will be called again when it becomes writable.

**Comment by MichaelSuen-thePointer** [comment]
> It should just return, since it will be called again when it becomes writable.

Understood. Thanks a lot!
