### ISSUE TITLE
src/handle.c:17:21: error: lvalue required as left operand of assignment

### ISSUE THREAD

**Issue by Lockzhiner** [saghul/pyuv#277]
build pynu and show error for this:
==================================
In file included from src/pyuv.c:4:
src/common.c: In function ‘pyuv_PyUnicode_FSConverter’:
src/common.c:76:14: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
   76 |     if (size != strlen(data)) {
      |              ^~
In file included from src/pyuv.c:8:
src/handle.c: In function ‘resurrect_object’:
src/handle.c:17:21: error: lvalue required as left operand of assignment
   17 |     Py_REFCNT(self) = refcnt;
      |                     ^
In file included from src/pyuv.c:16:
src/stream.c: In function ‘pyuv__stream_write_sequence’:
src/stream.c:369:19: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
  369 |     if (buf_count > ARRAY_SIZE(ctx->viewsml))
      |                   ^
In file included from src/pyuv.c:23:
src/udp.c: In function ‘pyuv__udp_send_sequence’:
src/udp.c:321:19: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘long unsigned int’ [-Wsign-compare]
  321 |     if (buf_count > ARRAY_SIZE(ctx->viewsml))

**Comment by bigbencat** [comment]
https://github.com/saghul/pyuv/issues/271
